# Numpy Programming Assignment

part 1:Smart Array Facotry Task : Create a function that allows students to generate specific array types quickly using built in Numpy Methods

In [ ]:
import numpy as np

def array_factory(mode:str,shape:tuple,value=None):
    '''
    creates various numpy arrays based on the mode
    - 'zeros' : array filled with o.
    - 'ones   : array filed with 1.
    - 'full'  : array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'  .
    '''
    if(mode.lower()=='zeros'):
        return np.zeros(shape)
    elif (mode.lower()=='ones'):
        return np.ones(shape)   
    elif (mode.lower()=='full'):
        return np.full(shape,value)
    elif (mode.lower()=='identity'):
        return np.identity(shape[0])
    else:
        raise ValueError("Invalid mode")


print(array_factory('Ones',(3,3)))
print(array_factory('zeros',(3,3)))
print(array_factory('FULL',(3,3),9))
print(array_factory('identity',(3,3)))







[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


part 2 : The secure_reshape_and_stack Function
This function demostrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
def secure_reshape_and_stack(data1,data2,new_shape):
    '''
    1. Validates and converts inputs to numpy arrays
    2. Reshapes the first dataset to a specific dimension
    3. vertically stack both datasets ino one matrix   
    '''

    try:
        # Convert list into numpy array
        arr1=np.array(data1)
        arr2=np.array(data2)
        # convert numpy array into column array
        reshaped_arr1=arr1.reshape(new_shape[0],new_shape[1])
        
        # Vertical Stacking (vstach)
        combined_dataset=np.vstack((reshaped_arr1,arr2))
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"company-grade error :{e}")

print(secure_reshape_and_stack([[1,2,3,4,5,6]],[[1,2,3],[4,5,6]],(2,3)))
    

        

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
