# LEARNING NUMPY LIBARARIY


In [3]:
import numpy as np

x=[1,2,3,4]
print(type(x))
print("====================")
v=np.array(x)
print(type(v))
print(v.ndim)
print(v.shape)
print(v)
print()

print(v.reshape(-1,1))
print()
print(v.reshape(2,2))



<class 'list'>
<class 'numpy.ndarray'>
1
(4,)
[1 2 3 4]

[[1]
 [2]
 [3]
 [4]]

[[1 2]
 [3 4]]


In [4]:
m=np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12]])
print(m)
print(m.shape[0])
print(m.shape[1])
print(type(m))
print(m.ndim)
print(m.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
4
<class 'numpy.ndarray'>
2
(3, 4)


In [5]:
s=np.array(5)
print(s)
print(s.ndim)
print(s.shape)

5
0
()


In [6]:
vec=np.array([1,2,3,4])
vec[:]

array([1, 2, 3, 4])

In [7]:
def array_reshape(arr : list,rows : int,cols :int) -> list:
    try:
        arr=np.array(arr)
        return arr.reshape(rows,cols)
    except(TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")


In [8]:
vec=[1,2,3,4,5,6]

array_reshape(vec,2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
class C:
    x=3

o1=C()
print(o1)
print(str(o1))    

In [10]:
# TYPEs Priorty : OBJECT , STRINGS , FLOAT , INT , BOOL
# IF YOU HAVE MATRIX OF STRINGS BUT ON ITEM IS OBJECT THE MATRIX ITEMS WILL BE OBJECT

m=np.array([[1,2,3,4],
[5,6,7,8],
[9,10,True,12]])

fm=m.astype(float)
print(fm.dtype)
print(m.dtype)
print(fm)
print(m)




float64
int64
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10.  1. 12.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1 12]]


In [11]:
print(m[1,2])
print(m[1:3,0:2])

7
[[ 5  6]
 [ 9 10]]


In [12]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print()
matT=mat.T
print(matT)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
mat=np.zeros((3,4))
mat=np.full((3,3),10)
print(mat)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
def init_w(shape,value=0):
    return np.full(shape,value)

In [15]:
init_w((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
angle =np.arange(0,360,90)
angle

array([  0,  90, 180, 270])

In [17]:
np.random.random((3,3))

array([[0.48563985, 0.67231688, 0.75646487],
       [0.89134211, 0.41387811, 0.35410416],
       [0.09728623, 0.5722949 , 0.96623592]])

In [19]:
np.random.randn(3,3)

array([[ 0.23790987,  1.16205785,  1.44799393],
       [-2.56521224,  0.19175417, -0.06996059],
       [-1.63288573, -0.19117046,  0.15221971]])

In [29]:
np.random.rand(3,3)

array([[0.42948581, 0.80713784, 0.70057967],
       [0.08665409, 0.2540114 , 0.536863  ],
       [0.94936636, 0.66466932, 0.25953194]])

In [20]:
np.random.randint(0,10,20)

array([5, 9, 7, 7, 2, 2, 1, 4, 1, 7, 4, 1, 4, 7, 2, 7, 8, 0, 1, 8],
      dtype=int32)

In [27]:
print(np.random.choice([11,12,13,22,14,15],3))

[15 15 14]


## Encode and Decode (Compressed & Decode )
### Saving and Loading Multiple NumPy Arrays


In [32]:
mat1=np.ones((5,3))
mat2=np.zeros((5,3))
np.savez("np_file.npz",cat=mat1,dog=mat2)

In [34]:
with np.load("np_file.npz") as file:
    mat1=file['cat']
    mat2=file['dog']

print(mat1)
print(mat2)    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
m1=np.array(([[1,2,3],[0,0,0]]))
m2=np.array(([[1,2,3],[0,0,0]]))

print("Vertical stack \n",np.vstack((m1,m2)))
print("\nHorizontal stack \n",np.hstack((m1,m2)))

Vertical stack 
 [[1 2 3]
 [0 0 0]
 [1 2 3]
 [0 0 0]]

Horizontal stack 
 [[1 2 3 1 2 3]
 [0 0 0 0 0 0]]


In [ ]:
v1=np.array([1,2,3,4,5])
v2=np.array([2,4,3,4,10])

print(v1==v2)

[False False  True  True False]
True


In [46]:
np.array_equal(v1,v2)

False

## compare all items of array with specific number
if one item doesn't satisfy the condition -> function will return false 

In [ ]:

print(np.all(v1 >=2))

False


In [48]:
np.any(v1>7)

np.False_

### `np.isclose()`

`np.isclose()` checks whether two values or arrays are **close enough to each other** within a specified tolerance.

```python
np.isclose(v1, v2, atol=3)

In [ ]:
v1=np.array([1,2,3,4,5])
v2=np.array([2,4,3,4,10])
np.isclose(v1,v2,atol=3)

# print(np.dot(v1,v2)/(np.linalg.det(v1)*np.linalg(v2)))



array([ True,  True,  True,  True, False])

In [55]:
np.allclose(v1,v2,atol=1)

False

In [64]:
v=np.array([2,3,4,20])
condition=v>=4
list =v[condition] =1
print(condition)
print(list)

v = [1, 2, 3, 4, 5, 6]
vv=[item   for item in v if item>3]
print(vv)

[False False  True  True]
1
[4, 5, 6]


In [ ]:
v=np.array([2,3,4,20])
c=2
# This is the broadcasting
print(v+c)

[ 4  5  6 22]
