# LEARNING NUMPY LIBARARIY


In [43]:
import numpy as np

x=[1,2,3,4]
print(type(x))
print("====================")
v=np.array(x)
print(type(v))
print(v.ndim)
print(v.shape)
print(v)
print()

print(v.reshape(-1,1))
print()
print(v.reshape(2,2))



<class 'list'>
<class 'numpy.ndarray'>
1
(4,)
[1 2 3 4]

[[1]
 [2]
 [3]
 [4]]

[[1 2]
 [3 4]]


In [44]:
m=np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12]])
print(m)
print(m.shape[0])
print(m.shape[1])
print(type(m))
print(m.ndim)
print(m.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
4
<class 'numpy.ndarray'>
2
(3, 4)


In [45]:
s=np.array(5)
print(s)
print(s.ndim)
print(s.shape)

5
0
()


In [46]:
vec=np.array([1,2,3,4])
vec[:]

array([1, 2, 3, 4])

In [47]:
def array_reshape(arr : list,rows : int,cols :int) -> list:
    try:
        arr=np.array(arr)
        return arr.reshape(rows,cols)
    except(TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")


In [48]:
vec=[1,2,3,4,5,6]

array_reshape(vec,2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
class C:
    x=3

o1=C()
print(o1)
print(str(o1))    

In [62]:
# TYPEs Priorty : OBJECT , STRINGS , FLOAT , INT , BOOL
# IF YOU HAVE MATRIX OF STRINGS BUT ON ITEM IS OBJECT THE MATRIX ITEMS WILL BE OBJECT

m=np.array([[1,2,3,4],
[5,6,7,8],
[9,10,True,12]])

fm=m.astype(float)
print(fm.dtype)
print(m.dtype)
print(fm)
print(m)




float64
int64
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10.  1. 12.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1 12]]


In [63]:
print(m[1,2])
print(m[1:3,0:2])

7
[[ 5  6]
 [ 9 10]]


In [64]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print()
matT=mat.T
print(matT)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [67]:
mat=np.zeros((3,4))
mat=np.full((3,3),10)
print(mat)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
